//! Sites — standalone multi-page websites and landing pages
//!
//! Sites are publicly-accessible web pages generated by the AI agent.
//! Unlike canvases (which are internal UI views), sites are full HTML documents
//! served at public URLs with their own routing, SEO, and form handling.
//!
//! Forms on site pages can submit data directly into collections via the
//! `/s/{slug}/submit/{collection}` endpoint.

use amos_core::{AmosError, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value as JsonValue};
use sqlx::{PgPool, Row};
use uuid::Uuid;

// ── Types ────────────────────────────────────────────────────────────────

/// A site is a multi-page website served at a public URL.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Site {
    pub id: Uuid,
    pub name: String,
    pub slug: String,
    pub description: Option<String>,
    pub domain: Option<String>,
    pub is_published: bool,
    pub published_at: Option<DateTime<Utc>>,
    pub settings: JsonValue,
    pub metadata: JsonValue,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A page within a site.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Page {
    pub id: Uuid,
    pub site_id: Uuid,
    pub path: String,
    pub title: String,
    pub description: Option<String>,
    pub html_content: String,
    pub css_content: Option<String>,
    pub js_content: Option<String>,
    pub meta_title: Option<String>,
    pub meta_description: Option<String>,
    pub og_image: Option<String>,
    pub form_collection: Option<String>,
    pub sort_order: i32,
    pub is_published: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

// ── Site Engine ──────────────────────────────────────────────────────────

/// Engine for managing sites and pages.
pub struct SiteEngine {
    db_pool: PgPool,
}

impl SiteEngine {
    pub fn new(db_pool: PgPool) -> Self {
        Self { db_pool }
    }

    // ─── Site operations ─────────────────────────────────────────────

    /// Create a new site.
    pub async fn create_site(
        &self,
        name: &str,
        slug: &str,
        description: Option<&str>,
        settings: Option<JsonValue>,
    ) -> Result<Site> {
        let settings = settings.unwrap_or_else(|| json!({}));

        let row = sqlx::query(
            r#"INSERT INTO sites (name, slug, description, settings)
               VALUES ($1, $2, $3, $4)
               RETURNING id, name, slug, description, domain, is_published, published_at,
                         settings, metadata, created_at, updated_at"#,
        )
        .bind(name)
        .bind(slug)
        .bind(description)
        .bind(&settings)
        .fetch_one(&self.db_pool)
        .await
        .map_err(|e| AmosError::Internal(format!("Failed to create site: {}", e)))?;

        site_from_row(&row)
    }

    /// Get a site by slug.
    pub async fn get_site(&self, slug: &str) -> Result<Site> {
        let row = sqlx::query(
            r#"SELECT id, name, slug, description, domain, is_published, published_at,
                      settings, metadata, created_at, updated_at
               FROM sites WHERE slug = $1"#,
        )
        .bind(slug)
        .fetch_optional(&self.db_pool)
        .await
        .map_err(|e| AmosError::Internal(format!("Failed to get site: {}", e)))?
        .ok_or_else(|| AmosError::NotFound {
            entity: "Site".to_string(),
            id: slug.to_string(),
        })?;

        site_from_row(&row)
    }

    /// List all sites.
    pub async fn list_sites(&self) -> Result<Vec<Site>> {
        let rows = sqlx::query(
            r#"SELECT id, name, slug, description, domain, is_published, published_at,
                      settings, metadata, created_at, updated_at
               FROM sites ORDER BY created_at DESC"#,
        )
        .fetch_all(&self.db_pool)
        .await
        .map_err(|e| AmosError::Internal(format!("Failed to list sites: {}", e)))?;

        rows.iter().map(site_from_row).collect()
    }

    /// Update site settings/metadata.
    pub async fn update_site(
        &self,
        slug: &str,
        name: Option<&str>,
        description: Option<&str>,
        domain: Option<&str>,
        settings: Option<JsonValue>,
    ) -> Result<Site> {
        // Build dynamic update — only set fields that are provided
        let row = sqlx::query(
            r#"UPDATE sites SET
                name = COALESCE($2, name),
                description = COALESCE($3, description),
                domain = COALESCE($4, domain),
                settings = COALESCE($5, settings),
                updated_at = NOW()
               WHERE slug = $1
               RETURNING id, name, slug, description, domain, is_published, published_at,
                         settings, metadata, created_at, updated_at"#,
        )
        .bind(slug)
        .bind(name)
        .bind(description)
        .bind(domain)
        .bind(&settings)
        .fetch_optional(&self.db_pool)
        .await
        .map_err(|e| AmosError::Internal(format!("Failed to update site: {}", e)))?
        .ok_or_else(|| AmosError::NotFound {
            entity: "Site".to_string(),
            id: slug.to_string(),
        })?;

        site_from_row(&row)
    }

    /// Publish or unpublish a site.
    pub async fn publish_site(&self, slug: &str, publish: bool) -> Result<Site> {
        let published_at: Option<DateTime<Utc>> = if publish { Some(Utc::now()) } else { None };

        let row = sqlx::query(
            r#"UPDATE sites SET
                is_published = $2,
                published_at = COALESCE($3, published_at),
                updated_at = NOW()
               WHERE slug = $1
               RETURNING id, name, slug, description, domain, is_published, published_at,
                         settings, metadata, created_at, updated_at"#,
        )
        .bind(slug)
        .bind(publish)
        .bind(published_at)
        .fetch_optional(&self.db_pool)
        .await
        .map_err(|e| AmosError::Internal(format!("Failed to publish site: {}", e)))?
        .ok_or_else(|| AmosError::NotFound {
            entity: "Site".to_string(),
            id: slug.to_string(),
        })?;

        site_from_row(&row)
    }

    // ─── Page operations ─────────────────────────────────────────────

    /// Create or update a page (upsert by site_id + path).
    pub async fn upsert_page(
        &self,
        site_slug: &str,
        path: &str,
        title: &str,
        description: Option<&str>,
        html_content: &str,
        css_content: Option<&str>,
        js_content: Option<&str>,
        meta_title: Option<&str>,
        meta_description: Option<&str>,
        form_collection: Option<&str>,
    ) -> Result<Page> {
        let site = self.get_site(site_slug).await?;

        // Normalize path — ensure leading slash
        let path = if path.starts_with('/') {
            path.to_string()
        } else {
            format!("/{}", path)
        };

        let row = sqlx::query(
            r#"INSERT INTO pages (site_id, path, title, description, html_content,
                                  css_content, js_content, meta_title, meta_description,
                                  form_collection)
               VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
               ON CONFLICT (site_id, path) DO UPDATE SET
                   title = EXCLUDED.title,
                   description = COALESCE(EXCLUDED.description, pages.description),
                   html_content = EXCLUDED.html_content,
                   css_content = COALESCE(EXCLUDED.css_content, pages.css_content),
                   js_content = COALESCE(EXCLUDED.js_content, pages.js_content),
                   meta_title = COALESCE(EXCLUDED.meta_title, pages.meta_title),
                   meta_description = COALESCE(EXCLUDED.meta_description, pages.meta_description),
                   form_collection = COALESCE(EXCLUDED.form_collection, pages.form_collection),
                   updated_at = NOW()
               RETURNING id, site_id, path, title, description, html_content,
                         css_content, js_content, meta_title, meta_description, og_image,
                         form_collection, sort_order, is_published, created_at, updated_at"#,
        )
        .bind(site.id)
        .bind(&path)
        .bind(title)
        .bind(description)
        .bind(html_content)
        .bind(css_content)
        .bind(js_content)
        .bind(meta_title)
        .bind(meta_description)
        .bind(form_collection)
        .fetch_one(&self.db_pool)
        .await
        .map_err(|e| AmosError::Internal(format!("Failed to upsert page: {}", e)))?;

        page_from_row(&row)
    }

    /// Get a specific page by site slug and path.
    pub async fn get_page(&self, site_slug: &str, path: &str) -> Result<(Site, Page)> {
        let site = self.get_site(site_slug).await?;

        let path = if path.starts_with('/') {
            path.to_string()
        } else {
            format!("/{}", path)
        };

        let row = sqlx::query(
            r#"SELECT id, site_id, path, title, description, html_content,
                      css_content, js_content, meta_title, meta_description, og_image,
                      form_collection, sort_order, is_published, created_at, updated_at
               FROM pages WHERE site_id = $1 AND path = $2"#,
        )
        .bind(site.id)
        .bind(&path)
        .fetch_optional(&self.db_pool)
        .await
        .map_err(|e| AmosError::Internal(format!("Failed to get page: {}", e)))?
        .ok_or_else(|| AmosError::NotFound {
            entity: "Page".to_string(),
            id: format!("{}{}", site_slug, path),
        })?;

        Ok((site, page_from_row(&row)?))
    }

    /// List all pages for a site.
    pub async fn list_pages(&self, site_slug: &str) -> Result<Vec<Page>> {
        let site = self.get_site(site_slug).await?;

        let rows = sqlx::query(
            r#"SELECT id, site_id, path, title, description, html_content,
                      css_content, js_content, meta_title, meta_description, og_image,
                      form_collection, sort_order, is_published, created_at, updated_at
               FROM pages WHERE site_id = $1
               ORDER BY sort_order, path"#,
        )
        .bind(site.id)
        .fetch_all(&self.db_pool)
        .await
        .map_err(|e| AmosError::Internal(format!("Failed to list pages: {}", e)))?;

        rows.iter().map(page_from_row).collect()
    }

    /// Delete a page.
    pub async fn delete_page(&self, site_slug: &str, path: &str) -> Result<()> {
        let site = self.get_site(site_slug).await?;

        let path = if path.starts_with('/') {
            path.to_string()
        } else {
            format!("/{}", path)
        };

        let result = sqlx::query("DELETE FROM pages WHERE site_id = $1 AND path = $2")
            .bind(site.id)
            .bind(&path)
            .execute(&self.db_pool)
            .await
            .map_err(|e| AmosError::Internal(format!("Failed to delete page: {}", e)))?;

        if result.rows_affected() == 0 {
            return Err(AmosError::NotFound {
                entity: "Page".to_string(),
                id: format!("{}{}", site_slug, path),
            });
        }

        Ok(())
    }

    // ─── Rendering ───────────────────────────────────────────────────

    /// Render a page as a full HTML document.
    pub fn render_page(&self, site: &Site, page: &Page) -> String {
        let title = html_escape(page.meta_title.as_deref().unwrap_or(&page.title));
        let description = html_escape(
            page.meta_description
                .as_deref()
                .or(page.description.as_deref())
                .unwrap_or(""),
        );
        let analytics_id = site.settings.get("analytics_id").and_then(|v| v.as_str());
        let theme_color = html_escape(
            site.settings
                .get("theme_color")
                .and_then(|v| v.as_str())
                .unwrap_or("#000000"),
        );

        let css_block = sanitize_css_content(page.css_content.as_deref().unwrap_or(""));
        let js_block = sanitize_js_content(page.js_content.as_deref().unwrap_or(""));

        // Build the form submission script if the page has a form collection
        let form_script = if let Some(collection) = &page.form_collection {
            let safe_slug = html_escape(&site.slug);
            let safe_collection = html_escape(collection);
            format!(
                r#"<script>
document.addEventListener('DOMContentLoaded', function() {{
    document.querySelectorAll('form[data-collection]').forEach(function(form) {{
        form.addEventListener('submit', function(e) {{
            e.preventDefault();
            const formData = new FormData(form);
            const data = Object.fromEntries(formData.entries());
            fetch('/s/{slug}/submit/{collection}', {{
                method: 'POST',
                headers: {{ 'Content-Type': 'application/json' }},
                body: JSON.stringify(data)
            }})
            .then(r => r.json())
            .then(result => {{
                if (result.success) {{
                    const msg = form.querySelector('.form-success') || document.createElement('div');
                    msg.className = 'form-success';
                    msg.textContent = result.message || 'Submitted successfully!';
                    if (!form.contains(msg)) form.appendChild(msg);
                    form.reset();
                }} else {{
                    alert(result.error || 'Submission failed');
                }}
            }})
            .catch(() => alert('Network error'));
        }});
    }});
}});
</script>"#,
                slug = safe_slug,
                collection = safe_collection
            )
        } else {
            String::new()
        };

        // Only include analytics if the ID passes validation
        let analytics_block = match analytics_id {
            Some(ga_id) if is_valid_analytics_id(ga_id) => {
                format!(
                    r#"<script async src="https://www.googletagmanager.com/gtag/js?id={id}"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','{id}');</script>"#,
                    id = ga_id
                )
            }
            _ => String::new(),
        };

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' https: data:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' https: data:; font-src 'self' https: data:;">
    <title>{title}</title>
    <meta name="description" content="{description}">
    <meta name="theme-color" content="{theme_color}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <style>{css}</style>
    {analytics}
</head>
<body>
{html}
{form_script}
<script>{js}</script>
</body>
</html>"#,
            title = title,
            description = description,
            theme_color = theme_color,
            css = css_block,
            analytics = analytics_block,
            html = page.html_content,
            form_script = form_script,
            js = js_block,
        )
    }
}

// ── Security helpers ────────────────────────────────────────────────────

/// Escape HTML special characters to prevent XSS
fn html_escape(input: &str) -> String {
    input
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

/// Sanitize CSS content to prevent breaking out of <style> tag
fn sanitize_css_content(input: &str) -> String {
    input.replace("</style", "&lt;/style")
}

/// Sanitize JS content to prevent breaking out of <script> tag
fn sanitize_js_content(input: &str) -> String {
    input.replace("</script", "<\\/script")
}

/// Validate that an analytics ID matches known formats
fn is_valid_analytics_id(id: &str) -> bool {
    // Google Analytics 4: G-XXXXXXXXXX
    // Universal Analytics: UA-XXXXXXXX-X
    if id.starts_with("G-") {
        return id.len() <= 20 && id[2..].chars().all(|c| c.is_ascii_alphanumeric());
    }
    if id.starts_with("UA-") {
        return id.len() <= 20 && id[3..].chars().all(|c| c.is_ascii_digit() || c == '-');
    }
    false
}

// ── Row helpers ──────────────────────────────────────────────────────────

fn site_from_row(row: &sqlx::postgres::PgRow) -> Result<Site> {
    Ok(Site {
        id: row.get("id"),
        name: row.get("name"),
        slug: row.get("slug"),
        description: row.get("description"),
        domain: row.get("domain"),
        is_published: row.get("is_published"),
        published_at: row.get("published_at"),
        settings: row.get("settings"),
        metadata: row.get("metadata"),
        created_at: row.get("created_at"),
        updated_at: row.get("updated_at"),
    })
}

fn page_from_row(row: &sqlx::postgres::PgRow) -> Result<Page> {
    Ok(Page {
        id: row.get("id"),
        site_id: row.get("site_id"),
        path: row.get("path"),
        title: row.get("title"),
        description: row.get("description"),
        html_content: row.get("html_content"),
        css_content: row.get("css_content"),
        js_content: row.get("js_content"),
        meta_title: row.get("meta_title"),
        meta_description: row.get("meta_description"),
        og_image: row.get("og_image"),
        form_collection: row.get("form_collection"),
        sort_order: row.get("sort_order"),
        is_published: row.get("is_published"),
        created_at: row.get("created_at"),
        updated_at: row.get("updated_at"),
    })
}

// ── Tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;
    use serde_json::json;
    use uuid::Uuid;

    fn test_site() -> Site {
        Site {
            id: Uuid::new_v4(),
            name: "My Site".to_string(),
            slug: "my-site".to_string(),
            description: Some("A test site".to_string()),
            domain: None,
            is_published: false,
            published_at: None,
            settings: json!({}),
            metadata: json!({}),
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    fn test_page() -> Page {
        Page {
            id: Uuid::new_v4(),
            site_id: Uuid::new_v4(),
            path: "/".to_string(),
            title: "Home".to_string(),
            description: Some("Welcome page".to_string()),
            html_content: "<h1>Hello World</h1>".to_string(),
            css_content: Some("h1 { color: red; }".to_string()),
            js_content: Some("console.log('hi');".to_string()),
            meta_title: None,
            meta_description: None,
            og_image: None,
            form_collection: None,
            sort_order: 0,
            is_published: true,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    // ── render_page ──────────────────────────────────────────────────

    #[test]
    fn render_page_produces_complete_html() {
        // SiteEngine::render_page is &self but only reads site/page, no db
        // We can't construct SiteEngine without a PgPool, so we test the
        // rendering logic by calling it via a helper. Since render_page
        // doesn't touch self.db_pool, we verify the format directly.
        let site = test_site();
        let page = test_page();

        // Inline the rendering logic expectations
        let html = render_page_standalone(&site, &page);

        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<title>Home</title>"));
        assert!(html.contains("<h1>Hello World</h1>"));
        assert!(html.contains("h1 { color: red; }"));
        assert!(html.contains("console.log('hi');"));
        assert!(html.contains("charset=\"UTF-8\""));
        assert!(html.contains("viewport"));
    }

    #[test]
    fn render_page_uses_meta_title_when_set() {
        let site = test_site();
        let mut page = test_page();
        page.meta_title = Some("Custom Meta Title".to_string());

        let html = render_page_standalone(&site, &page);
        assert!(html.contains("<title>Custom Meta Title</title>"));
    }

    #[test]
    fn render_page_includes_meta_description() {
        let site = test_site();
        let mut page = test_page();
        page.meta_description = Some("SEO description here".to_string());

        let html = render_page_standalone(&site, &page);
        assert!(html.contains("SEO description here"));
    }

    #[test]
    fn render_page_includes_theme_color() {
        let mut site = test_site();
        site.settings = json!({"theme_color": "#ff6600"});
        let page = test_page();

        let html = render_page_standalone(&site, &page);
        assert!(html.contains("#ff6600"));
    }

    #[test]
    fn render_page_default_theme_color() {
        let site = test_site();
        let page = test_page();

        let html = render_page_standalone(&site, &page);
        assert!(html.contains("#000000"));
    }

    #[test]
    fn render_page_includes_analytics() {
        let mut site = test_site();
        site.settings = json!({"analytics_id": "G-TESTID123"});
        let page = test_page();

        let html = render_page_standalone(&site, &page);
        assert!(html.contains("G-TESTID123"));
        assert!(html.contains("googletagmanager.com"));
    }

    #[test]
    fn render_page_no_analytics_when_absent() {
        let site = test_site();
        let page = test_page();

        let html = render_page_standalone(&site, &page);
        assert!(!html.contains("googletagmanager.com"));
    }

    #[test]
    fn render_page_includes_form_script() {
        let site = test_site();
        let mut page = test_page();
        page.form_collection = Some("leads".to_string());

        let html = render_page_standalone(&site, &page);
        assert!(html.contains("/s/my-site/submit/leads"));
        assert!(html.contains("data-collection"));
    }

    #[test]
    fn render_page_no_form_script_when_absent() {
        let site = test_site();
        let page = test_page();

        let html = render_page_standalone(&site, &page);
        assert!(!html.contains("data-collection"));
    }

    #[test]
    fn render_page_handles_minimal_page() {
        let site = test_site();
        let mut page = test_page();
        page.css_content = None;
        page.js_content = None;
        page.description = None;

        let html = render_page_standalone(&site, &page);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<h1>Hello World</h1>"));
    }

    // ── Serde roundtrip ──────────────────────────────────────────────

    #[test]
    fn site_serde_roundtrip() {
        let site = test_site();
        let json = serde_json::to_value(&site).unwrap();
        let roundtripped: Site = serde_json::from_value(json).unwrap();
        assert_eq!(roundtripped.slug, "my-site");
        assert_eq!(roundtripped.name, "My Site");
    }

    #[test]
    fn page_serde_roundtrip() {
        let page = test_page();
        let json = serde_json::to_value(&page).unwrap();
        let roundtripped: Page = serde_json::from_value(json).unwrap();
        assert_eq!(roundtripped.title, "Home");
        assert_eq!(roundtripped.path, "/");
    }

    // ── Helper: standalone render (duplicates SiteEngine::render_page logic) ──

    fn render_page_standalone(site: &Site, page: &Page) -> String {
        let title = page.meta_title.as_deref().unwrap_or(&page.title);
        let description = page
            .meta_description
            .as_deref()
            .or(page.description.as_deref())
            .unwrap_or("");
        let analytics_id = site.settings.get("analytics_id").and_then(|v| v.as_str());
        let theme_color = site
            .settings
            .get("theme_color")
            .and_then(|v| v.as_str())
            .unwrap_or("#000000");

        let css_block = page.css_content.as_deref().unwrap_or("");
        let js_block = page.js_content.as_deref().unwrap_or("");

        let form_script = if let Some(collection) = &page.form_collection {
            format!(
                r#"<script>
document.addEventListener('DOMContentLoaded', function() {{
    document.querySelectorAll('form[data-collection]').forEach(function(form) {{
        form.addEventListener('submit', function(e) {{
            e.preventDefault();
            const formData = new FormData(form);
            const data = Object.fromEntries(formData.entries());
            fetch('/s/{slug}/submit/{collection}', {{
                method: 'POST',
                headers: {{ 'Content-Type': 'application/json' }},
                body: JSON.stringify(data)
            }})
            .then(r => r.json())
            .then(result => {{
                if (result.success) {{
                    const msg = form.querySelector('.form-success') || document.createElement('div');
                    msg.className = 'form-success';
                    msg.textContent = result.message || 'Submitted successfully!';
                    if (!form.contains(msg)) form.appendChild(msg);
                    form.reset();
                }} else {{
                    alert(result.error || 'Submission failed');
                }}
            }})
            .catch(() => alert('Network error'));
        }});
    }});
}});
</script>"#,
                slug = site.slug,
                collection = collection
            )
        } else {
            String::new()
        };

        let analytics_block = if let Some(ga_id) = analytics_id {
            format!(
                r#"<script async src="https://www.googletagmanager.com/gtag/js?id={id}"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','{id}');</script>"#,
                id = ga_id
            )
        } else {
            String::new()
        };

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="description" content="{description}">
    <meta name="theme-color" content="{theme_color}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <style>{css}</style>
    {analytics}
</head>
<body>
{html}
{form_script}
<script>{js}</script>
</body>
</html>"#,
            title = title,
            description = description,
            theme_color = theme_color,
            css = css_block,
            analytics = analytics_block,
            html = page.html_content,
            form_script = form_script,
            js = js_block,
        )
    }
}
